name: RSpec
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.6.x', '2.7.x']
    name: Test in Ruby ${{matrix.ruby}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.x'
      - run: |
          gem update --system
          npm install -g eslint
          bundle install 
          bundle exec rspec

